language: ruby

rvm:
  - 2.1
  - rbx-2
  - ruby-head

env:
  - COVERAGE=true

sudo: false

cache: bundler

services: mongodb

script: bundle exec rake errbit:bootstrap spec

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
